### PR TITLE
fix: noindex nofollow journeys

### PR DESCRIPTION
**Pull request by gdub01**
# Description

[www.jesusgiftcard.com](http://www.jesusgiftcard.com/) is indexed
[easter.jesusfilm.org](http://easter.jesusfilm.org/) is indexed
both are showing up in SERPS. Management requested this be blocked from serps at least for now. 
this adds noindex/nofollow to your.nextstep.is and your.nextstep.is/*
 

### <samp>🤖 Generated by Copilot at 1edfa87</samp>

This pull request updates the SEO settings of the journeys index page and the journey pages to prevent search engines from crawling and indexing them. It uses the `NextSeo` component from `next-seo` in the `index.tsx` and `[journeySlug].tsx` files.

- Link to Basecamp Todo

# How should this PR be QA Tested?

Please describe the QA tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

# Walkthrough

### <samp>🤖 Generated by Copilot at 1edfa87</samp>

*  Prevent search engines from crawling and indexing journey pages and journeys index page by adding `NextSeo` component with `nofollow` and `noindex` attributes ([link](https://github.com/JesusFilm/core/pull/1597/files?diff=unified&w=0#diff-37c5de598d6cb4b8178a9bb7d6e34e6deeda28cabf8ae09992f3c4f4a6ea2e15R36-R37), [link](https://github.com/JesusFilm/core/pull/1597/files?diff=unified&w=0#diff-7704898472a9a49a40503ef4bbac23b8f64cca8f7cb6006e59717d2f2f524be1R10), [link](https://github.com/JesusFilm/core/pull/1597/files?diff=unified&w=0#diff-7704898472a9a49a40503ef4bbac23b8f64cca8f7cb6006e59717d2f2f524be1L24-R40))
* Import `NextSeo` component from `next-seo` library in `index.tsx` file to use it in `JourneysPage` function ([link](https://github.com/JesusFilm/core/pull/1597/files?diff=unified&w=0#diff-7704898472a9a49a40503ef4bbac23b8f64cca8f7cb6006e59717d2f2f524be1R10))
* Wrap existing JSX elements in `JourneysPage` function with a fragment and add `NextSeo` component with SEO settings ([link](https://github.com/JesusFilm/core/pull/1597/files?diff=unified&w=0#diff-7704898472a9a49a40503ef4bbac23b8f64cca8f7cb6006e59717d2f2f524be1L24-R40))
* Add `NextSeo` component with SEO settings to `JourneyPage` function in `[journeySlug].tsx` file ([link](https://github.com/JesusFilm/core/pull/1597/files?diff=unified&w=0#diff-37c5de598d6cb4b8178a9bb7d6e34e6deeda28cabf8ae09992f3c4f4a6ea2e15R36-R37))

### CODE REVIEW

**Comment by gdub01** [comment]
@tataihono @storyworks any chance we can get this approved today? Just sounds like it needs to happen ASAP.

**Comment by tataihono** [comment]
Was there a Basecamp ticket for this? I didn't see this request come in. This could have negative implications for social media which need to be considered.

**Comment by gdub01** [comment]
> Was there a Basecamp ticket for this? I didn't see this request come in. This could have negative implications for social media which need to be considered.

@tataihono It just needs a review.

**Review by tanflem — APPROVED** [review]
Approved in slack conversation with Mike Shaw and Sway on June 5, 2023.

**Pull request merged**
