### PR TITLE
feat: aws vpn

### PR DESCRIPTION
**Pull request by mikeallisonJS**
# Description

This adds a vpn to the private subnet of AWS, allowing github actions to handle deployments and seeding

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged into main

### CODE REVIEW

**Comment by mikeallisonJS** [comment]
atlantis plan

**Review by tataihono — APPROVED** [review]

**Comment by mikeallisonJS** [comment]
atlantis apply

**Comment by mikeallisonJS** [comment]
atlantis apply

**Review by tataihono — APPROVED** [review]

**Comment by mikeallisonJS** [comment]
atlantis apply

**Review by tataihono — APPROVED** [review]

**Pull request merged**
