### PR TITLE
fix: add env variables to terraform

### PR DESCRIPTION
**Pull request by GeronimoJohn**
Add env variables for Algolia in terraform

### CODE REVIEW

**Comment by tataihono** [comment]
atlantis plan

**Comment by GeronimoJohn** [comment]
atlantis apply

**Review by scottkelso — APPROVED** [review]

**Comment by tataihono** [comment]
atlantis apply

**Comment by tataihono** [comment]
atlantis plan

**Comment by tataihono** [comment]
atlantis apply

**Comment by tataihono** [comment]
atlantis plan

**Comment by tataihono** [comment]
atlantis apply

**Comment by tataihono** [comment]
atlantis plan

**Comment by tataihono** [comment]
atlantis apply

**Pull request merged**
